main/urls.py
from django.urls import path
from .import views

app_name="main"

urlpatterns=[
    path('', views.home, name='home'),
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('added/', views.addlist, name='addlist'),
    path("search/", views.search, name='search'),
]

translate/urls.py

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

class List(models.Model):
    uzb = models.CharField(max_length=200)
    eng = models.CharField(max_length=200)
    
    def __str__(self):
        return (self.uzb)

main/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q

# Create your views here.
def home(request):
    return render(request, 'index.html')

def list(request):
    lists = List.objects.all()
    context = {
        'lists':lists
    }
    return render(request, 'list.html', context)

def add(request):
    return render(request, 'add.html')

def addlist(request):
    x = request.POST['uzb']
    y = request.POST['eng']
    contact = List(uzb=x, eng=y)
    contact.save()
    return render(request, 'index.html')


def search(request):
    q = request.GET.get("query")
    # print(type(q))
    if len(q) >= 2:
        query = List.objects.filter(
            Q(uzb__icontains=q) | Q(eng__icontains=q)
        )
        return render(request, "result.html", {"lists": query})
    return render(request, "result.html")

templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="section">
    <form action="http://127.0.0.1:8000/added/" method="post">
        {% csrf_token %}
        <div class="columns">
            <div class="column is-6">
                
                <label class="label">O'zbekchasi</label>
                <input class="input" required name="uzb" type="text" placeholder="Yozing">
            </div>
            <div class="column is-6">
                <label class="label">Inglizchasi</label>
                <input class="input" required name="eng" type="text" placeholder="Yozing">
            </div>
        </div>
        <div class="control">
            <button type="submit" class="button is-link">Yozish</button>
          </div>
    </form>

</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">  
    <title>Document</title>
</head>
<body>
    
    <!--NAVBAR  -->

    <nav class="navbar is-link" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="https://bulma.io">
            <img src="{% static 'mylogo.png' %}">
          </a>
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a href="/" class="navbar-item">
                Home
                </a>
      
                <a href="http://127.0.0.1:8000/list/" class="navbar-item">
                Mylist
                </a>
            </div>
      
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <a href="http://127.0.0.1:8000/add/" class="button is-primary">
                  <strong>Add list</strong>
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>    


      {% block content %}
      {% endblock %}

      <!-- footer -->


      
<footer class="footer is-fixed-bottom">
    <div class="content has-text-centered">
      <p>
        &copy; <strong>Fathiddin Mamadaliyev </strong> | 2022 
      </p>
    </div>
  </footer>


      <script src="{% static 'script.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="section">
<!-- search -->
<h1 class="title is-1">
    
    <center>
        Search <img src="{% static 'search.png' %}" width="40" alt="">
    </center>
</h1>

<script>
    function inlineSearch(query){
        console.log(query)
    }

</script>

<form action="{% url 'main:search' %}" method="get">
    <div class="columns">
        <div class="column is-9">
            <div class="field">
                <div class="control">
                  <input class="input" name="query" type="text" placeholder="Search text">
                </div>
            </div>
        
        </div>
        <div class="column is-3">
            <div class="field is-grouped">
                <div class="control">
                  <button type="submit" class="button is-link">Search</button>
                </div>
              </div>
        </div>
    </div>

</form>
    

</div>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="section">
    
<h1 class="title is-1">
    
    <center>
        Mylist <img src="{% static 'list.png' %}" width="50" alt="">
    </center>
</h1>
<table class="table" style="width: 100%;">
    <tr>
        <th>
            O'zbekchasi
        </th>
        <th>
            Inglizchasi
        </th>
    </tr>
    {% for x in lists %}

<tr>
    <td>
        {{x.uzb}}
    </td>
    <td>
        {{x.eng}}
    </td>
</tr>
    {% endfor %}
</table>
</div>


{% endblock %}

templates/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="section">
    {% if lists %}

<table class="table" style="width: 100%;">
    <tr>
        <th>
            O'zbekchasi
        </th>
        <th>
            Inglizchasi
        </th>
    </tr>
    
{% for x in lists %}
    <tr>
        
        <td>
            {{x.uzb}}
        </td>
        <td>
            {{x.eng}}
        </td>

    </tr>
{% endfor %}
</table>
{% else %}

<h1 class="title is-1">
    
    <center>
        Not Found
    </center>
</h1>
{% endif %}

</div>
{% endblock %}